// AUTO-GENERATED from the dance_styles table (the style registry).
// Do not edit by hand. To add or change styles: auto-manager Filament
// (Rules > Dance Styles), then run `npm run styles:generate`.

export const DANCE_STYLES = [
  "Afro",
  "Animation",
  "Breaking",
  "Chicago Footwork",
  "Dancehall",
  "Electro",
  "Heels",
  "Hip Hop",
  "House",
  "Hustle",
  "Jazz",
  "Jookin",
  "Krump",
  "Litefeet",
  "Locking",
  "Open Styles",
  "Popping",
  "Salsa",
  "Shuffling",
  "Swing",
  "Turfing",
  "Tutting",
  "Voguing",
  "Waacking",
  "Waving",
] as const;

export type DanceStyle = (typeof DANCE_STYLES)[number];

/** Lookup-key (lowercased, dash/underscore-folded) -> canonical name. */
export const STYLE_ALIASES: ReadonlyArray<readonly [string, DanceStyle]> = [
  ["afro dance", "Afro"],
  ["afrobeats", "Afro"],
  ["afro beats", "Afro"],
  ["afrodance", "Afro"],
  ["afro fusion", "Afro"],
  ["b boy", "Breaking"],
  ["b boying", "Breaking"],
  ["b boys", "Breaking"],
  ["b girl", "Breaking"],
  ["b girling", "Breaking"],
  ["b girls", "Breaking"],
  ["b.boy", "Breaking"],
  ["b.girl", "Breaking"],
  ["bboy", "Breaking"],
  ["bboying", "Breaking"],
  ["bboys", "Breaking"],
  ["bgirl", "Breaking"],
  ["bgirling", "Breaking"],
  ["bgirls", "Breaking"],
  ["break", "Breaking"],
  ["break battle", "Breaking"],
  ["break battles", "Breaking"],
  ["break danc", "Breaking"],
  ["break dance", "Breaking"],
  ["break dancing", "Breaking"],
  ["breakdance", "Breaking"],
  ["breakdancing", "Breaking"],
  ["breaker", "Breaking"],
  ["breakers", "Breaking"],
  ["breakin", "Breaking"],
  ["breaking battle", "Breaking"],
  ["power move", "Breaking"],
  ["power moves", "Breaking"],
  ["powermove", "Breaking"],
  ["powermoves", "Breaking"],
  ["rocking", "Breaking"],
  ["top rock", "Breaking"],
  ["toprock", "Breaking"],
  ["footwork", "Chicago Footwork"],
  ["juke footwork", "Chicago Footwork"],
  ["jukin", "Chicago Footwork"],
  ["dance hall", "Dancehall"],
  ["dh", "Dancehall"],
  ["ragga dancehall", "Dancehall"],
  ["electro dance", "Electro"],
  ["electrodance", "Electro"],
  ["milky way", "Electro"],
  ["tecktonik", "Electro"],
  ["heels dance", "Heels"],
  ["high heels", "Heels"],
  ["stiletto", "Heels"],
  ["hiphop", "Hip Hop"],
  ["jazz hip hop", "Hip Hop"],
  ["house dance", "House"],
  ["house dancing", "House"],
  ["jazz funk", "Jazz"],
  ["street jazz", "Jazz"],
  ["gangsta walk", "Jookin"],
  ["gangsta walking", "Jookin"],
  ["krumping", "Krump"],
  ["krumpin", "Krump"],
  ["lite feet", "Litefeet"],
  ["campbelllocking", "Locking"],
  ["campbellock", "Locking"],
  ["campbellocking", "Locking"],
  ["lock", "Locking"],
  ["lock and pop", "Locking"],
  ["locker", "Locking"],
  ["lockers", "Locking"],
  ["lockin", "Locking"],
  ["locking battle", "Locking"],
  ["all style", "Open Styles"],
  ["all styles", "Open Styles"],
  ["allstyle", "Open Styles"],
  ["allstyles", "Open Styles"],
  ["club style", "Open Styles"],
  ["clubstyle", "Open Styles"],
  ["freestyle", "Open Styles"],
  ["mix style", "Open Styles"],
  ["mixstyle", "Open Styles"],
  ["open division", "Open Styles"],
  ["open style", "Open Styles"],
  ["open weight", "Open Styles"],
  ["openstyle", "Open Styles"],
  ["openstyles", "Open Styles"],
  ["openweight", "Open Styles"],
  ["street dance", "Open Styles"],
  ["streetdance", "Open Styles"],
  ["bionic boogie", "Popping"],
  ["boogaloo", "Popping"],
  ["hand style", "Popping"],
  ["handstyle", "Popping"],
  ["pop", "Popping"],
  ["pop and lock", "Popping"],
  ["popper", "Popping"],
  ["poppers", "Popping"],
  ["poppin", "Popping"],
  ["popping battle", "Popping"],
  ["robot", "Popping"],
  ["roboting", "Popping"],
  ["shuffle", "Shuffling"],
  ["lindy hop", "Swing"],
  ["lindy", "Swing"],
  ["east coast swing", "Swing"],
  ["west coast swing", "Swing"],
  ["turf", "Turfing"],
  ["vogue", "Voguing"],
  ["ballroom", "Voguing"],
  ["ballroom vogue", "Voguing"],
  ["punking", "Waacking"],
  ["waack", "Waacking"],
  ["waak", "Waacking"],
  ["waaking", "Waacking"],
  ["wacking", "Waacking"],
  ["whack", "Waacking"],
  ["whacking", "Waacking"],
  ["waves", "Waving"],
];
