// AUTO-GENERATED from the dance_styles table (the style registry).
// Do not edit by hand. To add or change styles: auto-manager Filament
// (Rules > Dance Styles), then run `npm run styles:generate`.

export const DANCE_STYLES = [
  "Animation",
  "Breaking",
  "Chicago Footwork",
  "Dancehall",
  "Electro",
  "Hip Hop",
  "House",
  "Hustle",
  "Jazz",
  "Jookin",
  "Krump",
  "Litefeet",
  "Locking",
  "Open Styles",
  "Popping",
  "Salsa",
  "Shuffling",
  "Swing",
  "Turfing",
  "Tutting",
  "Voguing",
  "Waacking",
  "Waving",
] as const;

export type DanceStyle = (typeof DANCE_STYLES)[number];

/** Lookup-key (lowercased, dash/underscore-folded) -> canonical name. */
export const STYLE_ALIASES: ReadonlyArray<readonly [string, DanceStyle]> = [
  ["break dance", "Breaking"],
  ["break dancing", "Breaking"],
  ["breakdance", "Breaking"],
  ["breakdancing", "Breaking"],
  ["breakin", "Breaking"],
  ["b boy", "Breaking"],
  ["b girl", "Breaking"],
  ["bboy", "Breaking"],
  ["bgirl", "Breaking"],
  ["bboying", "Breaking"],
  ["bgirling", "Breaking"],
  ["break danc", "Breaking"],
  ["b.boy", "Breaking"],
  ["b.girl", "Breaking"],
  ["b boying", "Breaking"],
  ["b girling", "Breaking"],
  ["breaker", "Breaking"],
  ["breakers", "Breaking"],
  ["break battle", "Breaking"],
  ["break battles", "Breaking"],
  ["breaking battle", "Breaking"],
  ["footwork", "Chicago Footwork"],
  ["juke footwork", "Chicago Footwork"],
  ["jukin", "Chicago Footwork"],
  ["dance hall", "Dancehall"],
  ["ragga dancehall", "Dancehall"],
  ["tecktonik", "Electro"],
  ["milky way", "Electro"],
  ["hiphop", "Hip Hop"],
  ["jazz hip hop", "Hip Hop"],
  ["house dance", "House"],
  ["house dancing", "House"],
  ["jazz funk", "Jazz"],
  ["street jazz", "Jazz"],
  ["gangsta walk", "Jookin"],
  ["gangsta walking", "Jookin"],
  ["krumping", "Krump"],
  ["krumpin", "Krump"],
  ["lite feet", "Litefeet"],
  ["lockin", "Locking"],
  ["lock and pop", "Locking"],
  ["locker", "Locking"],
  ["lockers", "Locking"],
  ["locking battle", "Locking"],
  ["open style", "Open Styles"],
  ["all styles", "Open Styles"],
  ["open weight", "Open Styles"],
  ["openweight", "Open Styles"],
  ["open division", "Open Styles"],
  ["poppin", "Popping"],
  ["boogaloo", "Popping"],
  ["pop and lock", "Popping"],
  ["popper", "Popping"],
  ["poppers", "Popping"],
  ["popping battle", "Popping"],
  ["shuffle", "Shuffling"],
  ["lindy hop", "Swing"],
  ["lindy", "Swing"],
  ["east coast swing", "Swing"],
  ["west coast swing", "Swing"],
  ["turf", "Turfing"],
  ["vogue", "Voguing"],
  ["ballroom", "Voguing"],
  ["ballroom vogue", "Voguing"],
  ["waaking", "Waacking"],
  ["whacking", "Waacking"],
  ["waack", "Waacking"],
  ["waak", "Waacking"],
  ["whack", "Waacking"],
  ["waves", "Waving"],
];
